### ISSUE TITLE
Is libcork under active development?

### ISSUE THREAD

**Issue by aadityakalsi** [dcreager/libcork#101] opened 2015-06-13 11:43 UTC
I just wanted to understand if libcork is under active development and if not why?

Thanks

**Comment by dcreager** [comment] 2015-06-17 20:15
Yep, it is.  We're still using it for several internal projects here at RedJack.  There haven't been any major new features in awhile since the library has stabilized pretty well on what we need it to do.  Is there anything in particular that you find missing?

**Comment by aadityakalsi** [comment] 2015-06-17 22:20
The filesystem level APIs aren't comprehensive. Most of the things are covered, but things like setting file and directory timestamps, through either names, or descriptors, etc.

The filesystem APIs for path and directory listing don't account for filesystem encoding and as such assume ASCII.

Are their plans to support some or all of these things?

**Comment by wongsyrone** [comment] 2016-06-08 06:24
I still want to ask the same question after one year. Have libcork been tested on arm64(aarch64)?

**Comment by johnzachary** [comment] 2016-06-08 11:36
Hi all. At this time, @dcreager and I no longer work at RedJack. Since we were the main developers of libcork and several other libraries, it's unclear to us what RedJack plans to do with them.  I keep changes in my own fork, and @dcreager may as well.

@wongsyrone, as far as I know, libcork has not been tested on arm64(aarch64).

**Comment by rogers0** [comment] 2016-06-22 06:34
@wongsyrone unit test of libcork fails on [64-bit big endian arch] (https://buildd.debian.org/status/package.php?p=libcork) only, so for arm64 it should be okay.
What specific issue do you meet?

**Comment by wongsyrone** [comment] 2016-06-22 06:39
@rogers0 
segfault when starting a native arm64 program compiled with NDK r11c, the details goes [here](https://github.com/wongsyrone/shadowsocks-android/issues/1), the segfault disappears after switching back to the previous libcork. Any information is appreciated.

**Comment by wongsyrone** [comment] 2016-06-22 13:36
Finally, I find the root cause. The root cause is `__thread` not working on NDK r11c. It has been fixed in NDK r12. Sign. This issue really confused me several days.
BTW, big kudos to @dcreager.

**Comment by dcreager** [comment] 2016-06-22 14:00
If you can find any preprocessor macros that we could use to detect NDK r11c, then we could update the autodetection logic to not use `__thread` on that platform.  We already have a pthreads TLS implementation available as a fallback; we'd just have to tell `<libcork/threads/basics.h>` to use it.

**Comment by wongsyrone** [comment] 2016-06-22 14:24
I did some research, unfortunately, there has a file `source.properties` in $ANDROID_NDK_ROOT, which contains
```
Pkg.Desc = Android NDK
Pkg.Revision = 12.0.2931149
```
You can use `sed` to get the major version, in this case, `12`, is acceptable.

I haven't found any preprocessor macro defined NDK version atm, please let me know if there is one.

**Comment by dcreager** [comment] 2016-06-22 14:32
Yeah that will help if you want to skip libcork's autodetection and set all of the configuration macros yourself.  The autodetection logic purposefully only uses information that we can get via the preprocessor from the compiler toolchain itself, so that it works out of the box regardless of which build system you're using.  That does limit what it can detect, but also makes it easier to embed in other projects.

**Closed** 2017-10-26 01:30 UTC
